services:
  - type: web
    name: accessibility-testing-tool
    env: node
    buildCommand: |
      apt-get update && \
      apt-get install -y wget gnupg ca-certificates procps libxss1 && \
      npm ci && \
      npx playwright install-deps chromium && \
      npx playwright install chromium
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_GC
        value: "1"
    buildFilter:
      paths:
      - "**/*.js"
      - "package.json"
      - "package-lock.json"