services:
  - type: web
    name: accessibility-testing-tool
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
      - package.json
      - package-lock.json
      - "**/*.js"
      - "**/*.html"
      - "**/*.css" 