services:
  - type: web
    name: accessibility-testing-tool
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_GC
        value: "1"
    buildFilter:
      paths:
      - "**/*.js"
      - "package.json"
      - "package-lock.json"
      - "render-build.sh"